spring.application.name=hogwartsos
spring.datasource.url=jdbc:mariadb://localhost:3306/hogwartsDatabase
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update